// cc19-sprint.react-David-Mattia-Michael/src/components/AllPhotos.jsx
import React from "react";
import "../styles/photos.css";

export default function AllPhotos({ photos, getSinglePhoto }) {
  return (
    <>
      <div className="all-photos">
        {photos.map((photo, photoIndex) => {
          return (
            <img
              src={"data:image/png;base64," + photo}
              key={photoIndex}
              alt="broken"
              onClick={() => {
                getSinglePhoto(photoIndex);
              }}
            />
          );
        })}
      </div>
    </>
  );
}

// cc19-sprint.vue-Jay-Mattia/src/components/AllPhotos.vue
<template>
  <div className="all-photos">
    <img
      @click="handleSingles(photo)"
      v-for="photo in photos"
      :src="'data:image/jpeg;base64,' + photo"
      :alt="photo"
      v-bind:key="photo"
    />
  </div>
</template>

<script>
export default {
  name: "AllPhotos",
  props: {
    photos: Array
  },
  methods: {
    handleSingles(photo) {
      this.$emit("singles-in-your-area", photo);
    }
  }
};
</script>

<style scoped>
img {
  max-block-size: 200px;
  margin: 10px;
  cursor: pointer;
  transition: transform 0.2s;
}
img:hover {
  transform: scale(1.2);
}
</style>
